# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chatis' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chatis

pod ‘Firebase/Core’
pod ‘Firebase/Database’
pod ‘Firebase/Auth’

pod 'MessageKit'
pod 'JGProgressHUD'
pod 'RealmSwift'
pod 'SDWebImage'


end
